//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocScript.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Anthony Duguid")]
        public string App_Author {
            get {
                return ((string)(this["App_Author"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("anthonyduguid@gmail.com")]
        public string App_HelpEmail {
            get {
                return ((string)(this["App_HelpEmail"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST")]
        public string Script_Docbase {
            get {
                return ((string)(this["Script_Docbase"]));
            }
            set {
                this["Script_Docbase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\Update_keywords.dql")]
        public string Script_PathCodeFile {
            get {
                return ((string)(this["Script_PathCodeFile"]));
            }
            set {
                this["Script_PathCodeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Documentum\\product\\6.7\\bin")]
        public string Script_WorkingDirectory {
            get {
                return ((string)(this["Script_WorkingDirectory"]));
            }
            set {
                this["Script_WorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA3oPQUDIab0amb+Uv1r57ewAAAAACAAAAAAADZgAAwAAAABAAA" +
            "ABvWo3ObjcrD008fWfykmScAAAAAASAAACgAAAAEAAAALBCsGCuHAoDMBMrscr5i+0YAAAACmwjW3x47" +
            "Ac20ruoT7FYEQTyXSogqdtOFAAAABQPug5+tsKgmXBJbbOLNA7XeZYs")]
        public string Script_Functional_Password {
            get {
                return ((string)(this["Script_Functional_Password"]));
            }
            set {
                this["Script_Functional_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\Update_keywords_Results_TEST.txt")]
        public string Script_PathResultsFile {
            get {
                return ((string)(this["Script_PathResultsFile"]));
            }
            set {
                this["Script_PathResultsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idql64")]
        public string Script_CodeType {
            get {
                return ((string)(this["Script_CodeType"]));
            }
            set {
                this["Script_CodeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USERNAME")]
        public string Script_Functional_UserName {
            get {
                return ((string)(this["Script_Functional_UserName"]));
            }
            set {
                this["Script_Functional_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Script_ResultsFileLineOffset {
            get {
                return ((int)(this["Script_ResultsFileLineOffset"]));
            }
            set {
                this["Script_ResultsFileLineOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string App_PathDeploy {
            get {
                return ((string)(this["App_PathDeploy"]));
            }
            set {
                this["App_PathDeploy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_PathUserData {
            get {
                return ((string)(this["App_PathUserData"]));
            }
            set {
                this["App_PathUserData"] = value;
            }
        }
    }
}
